### ISSUE TITLE
Update to symphony 4

### ISSUE THREAD

**Issue by aolko** [ikoene/symfony-micro#2]
please update your requirements to symphony 4

**Comment by ikoene** [comment]
Updating to **Symfony 4** would require a lot of changes due to the new architecture. Furthermore, Symfony 4 has a micro approach by default, so it seems kinda superfluous to update anyway.

Just so you know, Symfony 3.4, which is [currently used](https://github.com/ikoene/symfony-micro/blob/master/composer.json#L12), is a **LTS version** (long term support) and is supported until 11/2020.

So in my opinion, it's best _not_ to update. I'm open to suggestions though.
